# Site settings
title: iris' journey
author:
  name: Iris Qu
  email: irisqu.831@gmail.com
description: "For my dad, mom, and Ethan"

# Build settings


  <ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>